name: Test

on:
  # Run the workflow on pull requests
  pull_request:
    branches:
      - main
  # Run the workflow on pushes to the main branch
  push:
    branches:
      - main

jobs:
  test:
    # Define the matrix for OS and PHP versions
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-24.04, windows-2025, macos-15 ]
        php: [ "8.1", "8.2", "8.3", "8.4" ]

    env:
      OS: ${{ matrix.os }}
      PHP: ${{ matrix.php }}

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v5
        with:
          # Fetch all history for all tags and branches
          fetch-depth: 0

      - name: "Set Xdebug coverage"
        run: echo "XDEBUG_MODE=coverage" >> $GITHUB_ENV

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: xdebug
          coverage: xdebug

      - name: "Display PHP and Composer version information"
        run: php --version && composer --version

      - name: "Install dependencies"
        run: composer install --no-interaction --no-progress --optimize-autoloader --prefer-dist

      - name: "Run PHPUnit tests"
        run: ./vendor/bin/phpunit

      - name: "Run SonarQube Scan"
        if: ${{ !cancelled() && matrix.os == 'ubuntu-24.04' && matrix.php == '8.4' }}
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
